package ar.edu.itba.paw.models;

public enum PagingSizes {
    MEDIA_DEFAULT_PAGE_SIZE(25),
    MOOVIE_LIST_DEFAULT_PAGE_SIZE_CARDS(24),
    MOOVIE_LIST_DEFAULT_PAGE_SIZE_CONTENT(25),
    FEATURED_MOOVIE_LIST_DEFAULT_TOTAL_CONTENT(100),
    TV_CREATOR_DEFAULT_PAGE_SIZE(25),
    DIRECTOR_DEFAULT_PAGE_SIZE(25),
    ACTOR_DEFAULT_PAGE_SIZE(25),
    GENRE_DEFAULT_PAGE_SIZE(26),
    PROVIDER_DEFAULT_PAGE_SIZE(25),
    REVIEW_DEFAULT_PAGE_SIZE(5),
    REPORT_DEFAULT_PAGE_SIZE(25),
    USER_LIST_DEFAULT_PAGE_SIZE(6),
    MILKY_LEADERBOARD_DEFAULT_PAGE_SIZE(25);

    private final int size;

    PagingSizes(int size) {
        this.size = size;
    }

    public int getSize() {
        return size;
    }
}
