@baseUrl = http://localhost:8080/list

#----------------------------
# GET
#----------------------------

### LIST BY ID

# EXAMPLE: GET {{base_url}}/list/5
@bearer_token = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjc0MDc0NywiZXhwIjoxNzMzMzQ1NTQ3fQ.OKFjYIuVZktDJ6rw3XbgW2aqO0brzGhjpOkU2sJJfgFVvauDxz7hCFwnVnUnJCW_ZW8EWw6BBfcg-AFyiCh_7Q
@id0 = 3

GET {{baseUrl}}/{{id0}}
Authorization: Bearer {{bearer_token}}

### LIST CONTENT

# EXAMPLE: {{baseUrl}}/list/1/content?orderBy=name&sortOrder=ASC&page=1

@id1 = 3
@orderBy1 = ASC
@sortOrder1 = name
@page1 = 1

GET {{baseUrl}}/{{id1}}/content?orderBy={{orderBy1}}&sortOrder={{sortOrder1}}&page={{page1}}
Authorization: Bearer {{bearer_token}}

### LIST LIST (Still needs a lot of work to be done aa)

@page2 = 1

GET {{baseUrl}}?pageNumber={{page2}}



#----------------------------
# POST
#----------------------------

### CREATE LIST

# POST http://localhost:8080/list
# Authorization: Bearer <your_token>
# Content-Type: application/json
#{
#  "name": "My Favorite Movies",
#  "description": "A collection of my favorite films."
#}

@bearer_token1 = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjc0MDc0NywiZXhwIjoxNzMzMzQ1NTQ3fQ.OKFjYIuVZktDJ6rw3XbgW2aqO0brzGhjpOkU2sJJfgFVvauDxz7hCFwnVnUnJCW_ZW8EWw6BBfcg-AFyiCh_7Q

POST {{baseUrl}}
Authorization: Bearer {{bearer_token1}}
Content-Type: application/json

{
  "name": "My Most hated but still Favorite MoviesaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaMy Most hated but still Favorite MoviesaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaMy Most hated but still Favorite MoviesaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaMy Most hated but still Favorite MoviesaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaMy Most hated but still Favorite MoviesaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaMy Most hated but still Favorite Moviesaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "description": "A collection of my favorite films."
}

> response.json



### INSERT MEDIA INTO LIST

# POST http://localhost:8080/list/{{moovieListId1}}/content
# Authorization: Bearer <your_token>
# Content-Type: application/json
#{
#  "name": "My Favorite Movies",
#  "description": "A collection of my favorite films."
#}

@bearer_token3 = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjc0MDc0NywiZXhwIjoxNzMzMzQ1NTQ3fQ.OKFjYIuVZktDJ6rw3XbgW2aqO0brzGhjpOkU2sJJfgFVvauDxz7hCFwnVnUnJCW_ZW8EWw6BBfcg-AFyiCh_7Q
@moovieListId1 = 4

POST {{baseUrl}}/{{moovieListId1}}/content
Authorization: Bearer {{bearer_token3}}
Content-Type: application/json

{
  "mediaIdList": [5,6,7,8]
}


### LIKE LIST

@moovieListId5 = 45

POST {{baseUrl}}/{{moovieListId5}}/like
Authorization: Bearer {{bearer_token3}}
Content-Type: application/json


### FOLLOW LIST

POST {{baseUrl}}/{{moovieListId5}}/follow
Authorization: Bearer {{bearer_token3}}
Content-Type: application/json


#----------------------------
# DELETE METHODS
#----------------------------

### DELETE LIST

@bearer_token2 = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjc0MDc0NywiZXhwIjoxNzMzMzQ1NTQ3fQ.OKFjYIuVZktDJ6rw3XbgW2aqO0brzGhjpOkU2sJJfgFVvauDxz7hCFwnVnUnJCW_ZW8EWw6BBfcg-AFyiCh_7Q

@id2 = 48

DELETE {{baseUrl}}/{{id2}}
Authorization: Bearer {{bearer_token2}}




### DELETE MEDIA FROM LIST

@bearer_token4 = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjc0MDc0NywiZXhwIjoxNzMzMzQ1NTQ3fQ.OKFjYIuVZktDJ6rw3XbgW2aqO0brzGhjpOkU2sJJfgFVvauDxz7hCFwnVnUnJCW_ZW8EWw6BBfcg-AFyiCh_7Q

@id4 = 45

DELETE {{baseUrl}}/{{id4}}/content
Authorization: Bearer {{bearer_token4}}
Content-Type: application/json

{
  "mediaIdList": [6]
}

