@baseUrl = http://localhost:8080/list

#----------------------------
# GET
#----------------------------

### LIST BY ID

# EXAMPLE: GET {{base_url}}/list/5

@id0 = 37

GET {{baseUrl}}/{{id0}}

### LIST CONTENT

# EXAMPLE: {{baseUrl}}/list/1/content?orderBy=name&sortOrder=ASC&page=1

@id1 = 37
@orderBy1 = ASC
@sortOrder1 = name
@page1 = 1

GET {{baseUrl}}/{{id1}}/content?orderBy={{orderBy1}}&sortOrder={{sortOrder1}}&page={{page1}}

### LIST LIST (Still needs a lot of work to be done aa)

@page2 = 1

GET {{baseUrl}}?pageNumber={{page2}}

#----------------------------
# POST
#----------------------------


### CREATE LIST

# POST http://localhost:8080/list
# Authorization: Bearer <your_token>
# Content-Type: application/json
#{
#  "name": "My Favorite Movies",
#  "description": "A collection of my favorite films."
#}

@bearer_token1 = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjc0MDc0NywiZXhwIjoxNzMzMzQ1NTQ3fQ.OKFjYIuVZktDJ6rw3XbgW2aqO0brzGhjpOkU2sJJfgFVvauDxz7hCFwnVnUnJCW_ZW8EWw6BBfcg-AFyiCh_7Q

POST {{baseUrl}}
Authorization: Bearer {{bearer_token1}}
Content-Type: application/json

{
  "name": "My Most hated but still Favorite Movies",
  "description": "A collection of my favorite films."
}

###

