@baseUrl = http://localhost:8080/review

#----------------------------
# GET
#----------------------------

### REVIEW BY ID

# EXAMPLE: GET {{baseUrl}}/review/123

@id0 = 1

GET {{baseUrl}}/{{id0}}


### MEDIA LIST

#----------------------------
# POST
#----------------------------
### LIKE REVIEW
@id1=6
@bearer_token1 =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJXYW5jaG8iLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjc0MDc0NywiZXhwIjoxNzMzMzQ1NTQ3fQ.OKFjYIuVZktDJ6rw3XbgW2aqO0brzGhjpOkU2sJJfgFVvauDxz7hCFwnVnUnJCW_ZW8EWw6BBfcg-AFyiCh_7Q

POST {{baseUrl}}/{{id1}}/like
Authorization: Bearer {{bearer_token1}}

#----------------------------
# DELETE
#----------------------------

### DELETE REVIEW
@id2=1
@bearer_token2 =  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNb292aWUiLCJhdXRob3JpemF0aW9uIjoiVVNFUiIsImlhdCI6MTczMjgzNjEyMiwiZXhwIjoxNzMzNDQwOTIyfQ.DH67__vKqJhHSWunS362U0O1qRptW4Gfjw35LCUqy0z8CtLlmIE-MaxkqXscQZQtE4ILqyEmRaiRaofmCXd4oA

DELETE {{baseUrl}}/{{id2}}
Authorization: Bearer {{bearer_token2}}



